apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  metrica_name: {{ .Values.metrica_name | toString | b64enc}}
  metrica_name: {{ .Values.policy_name | toString | b64enc}}
  metrica_name: {{ .Values.service_name | toString | b64enc}}
  topic_read: {{ .Values.topic_read | toString | b64enc }}
  topic_write: {{ .Values.topic_write | toString | b64enc }}
  operator: {{ .Values.operator | toString | b64enc }}
  check: {{ .Values.check | toString | b64enc }}
#toString to convert a int value 
  deltatime: {{ .Values.deltatime | toString | b64enc }}
  port_metrica: {{ .Values.port_metrica | toString | b64enc }}

  topic_read_policy: {{ .Values.topic_read_policy | toString | b64enc }}
  soglia: {{ .Values.soglia | toString| b64enc }}
#toString to convert a int value 
  port_policy: {{ .Values.port_policy | toString | b64enc }}

  process_id: {{ .Values.process_id | b64enc }}
  port_service: {{ .Values.port_service | toString | b64enc }}