apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  topic_read: {{ .Values.topic_read | toString | b64enc }}
  process_id: {{ .Values.process_id | toString | b64enc }}
  portTest: {{ .Values.portTest | toString | b64enc }}