apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-unico.msmetrica.fullname" . }}
  labels:
    {{- include "helm-unico.labels" . | nindent 4 }}
spec:
  type: {{ .Values.msmetrica.service.type }}
  ports:
    - port: {{ .Values.msmetrica.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.port_metrica }} 
      protocol: TCP
      name: http
  selector:
    {{- include "helm-unico.selectorLabels" . | nindent 4 }}
