apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  topic_read: {{ .Values.topic_read | toString | b64enc }}
  topic_write: {{ .Values.topic_write | toString | b64enc }}
  operator: {{ .Values.operator | toString | b64enc }}
  check: {{ .Values.check | toString | b64enc }}
#toString to convert a int value 
  deltatime: {{ .Values.deltatime | toString | b64enc }}
  process_id: {{ .Values.process_id | toString | b64enc }}

