apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mspolicy.fullname" . }}
  labels:
    {{- include "mspolicy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mspolicy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mspolicy.selectorLabels" . | nindent 8 }}
    spec:
      dnsPolicy: Default
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mspolicy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:          
          - name: "TOPIC_READ_POLICY"
            valueFrom:
              secretKeyRef:
                key:  topic_read_policy
                name: {{ .Release.Name }}-auth
          - name: "SOGLIA"
            valueFrom:
              secretKeyRef:
                key:  soglia
                name: {{ .Release.Name }}-auth
          - name: "PROCESS_ID"
            valueFrom:
              secretKeyRef:
                key:  process_id
                name: {{ .Release.Name }}-auth
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          livenessProbe:  
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
