apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  topic_read_policy: {{ .Values.topic_read_policy | toString | b64enc }}
  soglia: {{ .Values.soglia | toString| b64enc }}
#toString to convert a int value 
  process_id: {{ .Values.process_id | toString | b64enc }}
  portTest: {{ .Values.portTest | toString | b64enc }}
