apiVersion: v1
kind: Service
metadata:
  name: {{ include "mspolicy.fullname" . }}
  labels:
    {{- include "mspolicy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.portTest }} 
      protocol: TCP
      name: http
  selector:
    {{- include "mspolicy.selectorLabels" . | nindent 4 }}